### ISSUE TITLE
error

### ISSUE THREAD

**Issue by luxagen** [AndyLandy/MakeMP3#4]
**\* Applying album gain
... 04 Oh! Darling.mp3
... 02 I'm a Loser.mp3
... 03 Baby's in Black.mp3
... 05 Octopus's Garden.mp3
... 13 Everything I Wanted.mp3
... 04 Rock and Roll Music.mp3
... 06 I Want You (She's So Heavy).mp3
... 05 I'll Follow the Sun.mp3
... 06 Mr. Moonlight.mp3
... 14 Where Were You When I Needed You.mp3
... 07 Kansas City-Hey-Hey-Hey-Hey!.mp3
... 07 Here Comes the Sun.mp3
... 08 Eight Days a Week.mp3
**\* Applying album gain
Use of uninitialized value $v in substitution (s///) at /cygdrive/e/svn/makemp3/makemp3 line 279.
The Beatles - Free as a Bird:
... 01 Free as a Bird.mp3
... 08 Because.mp3
... 09 Words of Love.mp3
... 10 Honey Don't.mp3
... 09 You Never Give Me Your Money.mp3
... 02 I Saw Her Standing There [take 9 full version].mp3
... 11 Every Little Thing.mp3
... 10 Sun King.mp3
... 12 I Don't Want to Spoil the Party.mp3
... 03 This Boy [recording-session eavesdrop].mp3
... 11 Mean Mr. Mustard.mp3
... 12 Polythene Pam.mp3
... 13 What You're Doing.mp3

**Comment by AndyLandy** [comment]
> Use of uninitialized value $v in substitution (s///) at /cygdrive/e/svn/makemp3/makemp3 line 279.
> That looks like a malformed cue sheet has done that. If you have a directive with no content, this is the likely outcome. Do you know which track caused the error?

On a separate note, I also got this output:
... 07 Can't Buy Me Love.mp3
[NULL @ 0x7fcd79009a00] sample/frame number mismatch in adjacent frames
... 08 Any Time at All.mp3

I think I saw you got something similar? That’s ffmpeg throwing a wobbly at dodgy source material.

Not looked into any of your other errors yet. I’ll see what I can do.

Regards,

On 3 Mar 2016, at 18:11, luxagen <notifications@github.com<mailto:notifications@github.com>> wrote:

**\* Applying album gain
... 04 Oh! Darling.mp3
... 02 I'm a Loser.mp3
... 03 Baby's in Black.mp3
... 05 Octopus's Garden.mp3
... 13 Everything I Wanted.mp3
... 04 Rock and Roll Music.mp3
... 06 I Want You (She's So Heavy).mp3
... 05 I'll Follow the Sun.mp3
... 06 Mr. Moonlight.mp3
... 14 Where Were You When I Needed You.mp3
... 07 Kansas City-Hey-Hey-Hey-Hey!.mp3
... 07 Here Comes the Sun.mp3
... 08 Eight Days a Week.mp3
**\* Applying album gain
Use of uninitialized value $v in substitution (s///) at /cygdrive/e/svn/makemp3/makemp3 line 279.
The Beatles - Free as a Bird:
... 01 Free as a Bird.mp3
... 08 Because.mp3
... 09 Words of Love.mp3
... 10 Honey Don't.mp3
... 09 You Never Give Me Your Money.mp3
... 02 I Saw Her Standing There [take 9 full version].mp3
... 11 Every Little Thing.mp3
... 10 Sun King.mp3
... 12 I Don't Want to Spoil the Party.mp3
... 03 This Boy [recording-session eavesdrop].mp3
... 11 Mean Mr. Mustard.mp3
... 12 Polythene Pam.mp3
... 13 What You're Doing.mp3

—
Reply to this email directly or view it on GitHubhttps://github.com/AndyLandy/MakeMP3/issues/4.

## 

Andrew Paul Landells
Team Lead, iSolutions Technical Innovation & Developments Team: Web & Databases.
Telephone: 023 8059 6879 (x26879); Mobile: Please ring desk phone, which will divert.
For meetings, I will usually be on the Highfield Campus on Mondays, and at 1GS on Tuesdays, Thursdays and Fridays.
